PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Users" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Identifier" TEXT NOT NULL, "Username" TEXT NOT NULL, "Password" TEXT NOT NULL, "Salt" TEXT, "Iterations" INTEGER);
INSERT INTO Users VALUES(1,'9a6d2376-7b2b-4f81-9927-beef9b18b618','admin','Q2mwExdCTS4GDSUS1C6jRXtVSHk7BM/xd/KaR0tY5jY=','xriK3iQOdLb2shAt0qH/9g==',10000);
COMMIT;
