# Cloudflare Tunnel - Jellyfin Remote Access (optional)
# Usage: docker-compose -f docker-compose.yml -f docker-compose.cloudflare.yml up -d
services:
  # Cloudflare Tunnel - Jellyfin Remote Access (zero-config for new users)
  cloudflared:
    image: alpine:latest
    container_name: ${CONTAINER_PREFIX}cloudflared
    networks:
      - media_network
    volumes:
      - ./data/shared:/shared-data
      - ./config/jellyfin/tunnel-setup:/tunnel-setup:ro
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN:-}
    entrypoint: ["/tunnel-setup/smart-tunnel.sh"]
    depends_on:
      jellyfin:
        condition: service_healthy
    restart: unless-stopped