# Ngrok Tunnel - Jellyfin Remote Access (optional)
# Usage: docker-compose -f docker-compose.yml -f docker-compose.ngrok.yml up -d
services:
  # Ngrok Tunnel - Alternative Jellyfin Remote Access (zero-config for new users)
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ${CONTAINER_PREFIX}ngrok
    networks:
      - media_network
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN:-}
      - NGROK_DOMAIN=${NGROK_DOMAIN:-}
    entrypoint: ["/ngrok-setup/smart-ngrok.sh"]
    volumes:
      - ./config/jellyfin/ngrok/smart-ngrok.sh:/ngrok-setup/smart-ngrok.sh:ro
      - ./data/shared:/shared-data
    depends_on:
      jellyfin:
        condition: service_healthy
    restart: unless-stopped