# Watchlistarr Configuration Template
# Automatically syncs Plex watchlists with Sonarr (TV) and Radarr (movies)
# Environment variables will be substituted at container startup

# Sync interval configuration
interval:
  seconds: 60

# Sonarr configuration for TV shows
sonarr:
  baseUrl: "http://sonarr:8989"
  apikey: "624fe2507ddb4a8bbf1d8924b0e07b17"
  qualityProfile: "Any"
  rootFolder: "/tv"
  bypassIgnored: false
  seasonMonitoring: "all"
  tags:
    - watchlistarr

# Radarr configuration for movies
radarr:
  baseUrl: "http://radarr:7878"
  apikey: "21861064a2834ef08f7c2f26957af672"
  qualityProfile: "Any"
  rootFolder: "/movies"
  bypassIgnored: false
  tags:
    - watchlistarr

# Plex configuration
plex:
  token: "gjyy4Fx3Qv_Msy9hWChe"
  skipfriendsync: false

# Delete sync configuration - ENABLED BY DEFAULT
# Removes content from Sonarr/Radarr when removed from Plex watchlist
delete:
  movie: false
  endedShow: false
  continuingShow: false
  interval:
    days: 7
  deleteFiles: false

# Logging configuration
logging:
  level: "INFO"
  file: "/app/logs/watchlistarr.log"
